[package]
name = "castra-vizier"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.58"
time = { version = "0.3.36", features = ["formatting"] }
